#!/usr/bin/env bash
set -euo pipefail

WORK_ROOT="/media/molloi-lab/2TB4/Artin/right_leg_corrected_50um_full_20260615_1453"
REPO="${WORK_ROOT}/repo/VascularTreeSim.jl"
INPUT="${WORK_ROOT}/input/both_legs_xcat_input"
STAMP="$(date +%Y%m%d_%H%M%S)"

TERMINAL_UM="${VTS_TERMINAL_UM:-20.0}"
TERMINAL_TAG="$(printf '%s' "${TERMINAL_UM}" | sed 's/\./p/g')um"
OUT="${WORK_ROOT}/output/right_leg_biology_first_${TERMINAL_TAG}_explicit_${STAMP}"
LOG_DIR="${WORK_ROOT}/logs"
LOG="${LOG_DIR}/right_leg_biology_first_${TERMINAL_TAG}_explicit_${STAMP}.log"

FRONTIER_BATCH="${VTS_FRONTIER_BATCH:-4096}"
GRAPH_BLOCK_SIZE="${VTS_GRAPH_BLOCK_SIZE:-1}"
MIN_FRONTIER_SEPARATION_CM="${VTS_MIN_FRONTIER_SEPARATION_CM:-0.005}"
MAX_SEGMENT_LENGTH_CM="${VTS_MAX_SEGMENT_LENGTH_CM:-0.05}"
GRAPH_NEIGHBORS="${VTS_GRAPH_NEIGHBORS:-24}"
MAX_PATH_NODES="${VTS_MAX_PATH_NODES:-64}"
GRAPH_JITTER_CM="${VTS_GRAPH_JITTER_CM:-0.005}"
SNAP_TERMINAL_TO_TARGET="${VTS_SNAP_TERMINAL_TO_TARGET:-true}"
MAX_TERMINAL_SNAP_CM="${VTS_MAX_TERMINAL_SNAP_CM:-0.15}"
COVERAGE_MULTIPLIER="${VTS_COVERAGE_MULTIPLIER:-1.25}"
USE_INDEXED_ANCHOR="${VTS_USE_INDEXED_ANCHOR:-true}"
USE_ASTAR_ROUTING="${VTS_USE_ASTAR_ROUTING:-true}"
FRONTIER_CANDIDATE_FACTOR="${VTS_FRONTIER_CANDIDATE_FACTOR:-64}"
FIXED_VEIN_EXPORTS="${VTS_FIXED_VEIN_EXPORTS:-6}"
MAX_ANCHOR_GAP_CM="${VTS_MAX_ANCHOR_GAP_CM:-1.25}"
GROWTH_ARTERY_SEEDS="${VTS_GROWTH_ARTERY_SEEDS:-0}"
GROWTH_ARTERY_MIN_LENGTH_CM="${VTS_GROWTH_ARTERY_MIN_LENGTH_CM:-3.0}"
FIXED_ARTERY_MIN_LENGTH_CM="${VTS_FIXED_ARTERY_MIN_LENGTH_CM:-3.0}"
FIXED_VEIN_MIN_LENGTH_CM="${VTS_FIXED_VEIN_MIN_LENGTH_CM:-8.0}"
TARGET="${VTS_TARGET_BRANCHES:-auto}"

mkdir -p "${OUT}" "${LOG_DIR}"
cd "${REPO}"

export JULIA_DEPOT_PATH="/media/molloi-lab/2TB4/Artin/julia_depot"
export JULIA_NUM_THREADS="${JULIA_NUM_THREADS:-16}"
export CUDA_DEVICE_ORDER="PCI_BUS_ID"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export VTS_CHECKPOINT_DIR="${OUT}/checkpoints"
export VTS_CHECKPOINT_INTERVAL_SECONDS="${VTS_CHECKPOINT_INTERVAL_SECONDS:-1800}"
export VTS_CHECKPOINT_KEEP="${VTS_CHECKPOINT_KEEP:-3}"

export VTS_BIOLOGY_FIRST="true"
export VTS_TARGET_BRANCH_COUNT_MODE="${VTS_TARGET_BRANCH_COUNT_MODE:-explicit}"
export VTS_ALLOW_POST_GROWTH_SUBDIVISION="${VTS_ALLOW_POST_GROWTH_SUBDIVISION:-false}"
export VTS_ADAPTIVE_BRANCH_CAPS="${VTS_ADAPTIVE_BRANCH_CAPS:-true}"
export VTS_MIN_EXPLICIT_ROUTED_TERMINAL_UM="${VTS_MIN_EXPLICIT_ROUTED_TERMINAL_UM:-20.0}"
export VTS_TERMINAL_BED_DIAMETER_UM="${VTS_TERMINAL_BED_DIAMETER_UM:-${TERMINAL_UM}}"
export VTS_TERMINAL_BED_LENGTH_CM="${VTS_TERMINAL_BED_LENGTH_CM:-0.05}"
if [[ -n "${VTS_TERMINAL_BED_MODE:-}" ]]; then
    export VTS_TERMINAL_BED_MODE
fi
if [[ -n "${VTS_EXPLICIT_TERMINAL_UM:-}" ]]; then
    export VTS_EXPLICIT_TERMINAL_UM
fi
if [[ -n "${VTS_FLOW_EXPLICIT_MIN_DIAMETER_UM:-}" ]]; then
    export VTS_FLOW_EXPLICIT_MIN_DIAMETER_UM
fi
if [[ -n "${VTS_TOPOLOGY_AUDIT_MIN_DIAMETER_UM:-}" ]]; then
    export VTS_TOPOLOGY_AUDIT_MIN_DIAMETER_UM
fi
export VTS_SUBDIVIDE_XCAT_TERMINALS="${VTS_SUBDIVIDE_XCAT_TERMINALS:-false}"

export VTS_XCAT_NRB_PATH="${VTS_XCAT_NRB_PATH:-${INPUT}/both_legs_1.nrb}"
export VTS_XCAT_VESSEL_SOURCE="${VTS_XCAT_VESSEL_SOURCE:-nrb}"
export VTS_NRB_DOMAIN_VOXEL_SPACING_CM="${VTS_NRB_DOMAIN_VOXEL_SPACING_CM:-0.1}"
export VTS_NRB_DOMAIN_SAMPLES="${VTS_NRB_DOMAIN_SAMPLES:-48,48}"
export VTS_ROUTE_DILATION_VOXELS="${VTS_ROUTE_DILATION_VOXELS:-0}"
export VTS_MAX_GRAPH_BLOCK_SIZE="${VTS_MAX_GRAPH_BLOCK_SIZE:-1}"
export VTS_MIN_GRAPH_LARGEST_COMPONENT_FRACTION="${VTS_MIN_GRAPH_LARGEST_COMPONENT_FRACTION:-0.95}"
export VTS_MAX_UNCLAIMED_TARGET_FRACTION="${VTS_MAX_UNCLAIMED_TARGET_FRACTION:-0.02}"

export VTS_TARGET_TISSUE_MODE="${VTS_TARGET_TISSUE_MODE:-soft}"
export VTS_TARGET_DEMAND_MODE="${VTS_TARGET_DEMAND_MODE:-weighted}"
export VTS_TARGET_DEMAND_WEIGHTS="${VTS_TARGET_DEMAND_WEIGHTS:-muscle=1.0,skin=0.05,fat=0.02,envelope=0.03,other_soft=0.05}"
export VTS_MAX_COVERAGE_POINTS="${VTS_MAX_COVERAGE_POINTS:-5000000}"

export VTS_DISTAL_MURRAY_GAMMA="${VTS_DISTAL_MURRAY_GAMMA:-3.0}"
export VTS_PROXIMAL_MURRAY_GAMMA="${VTS_PROXIMAL_MURRAY_GAMMA:-2.0}"
export VTS_MURRAY_TRANSITION_UM="${VTS_MURRAY_TRANSITION_UM:-200.0}"

export VTS_MAX_BRANCH_LENGTH_CM="${VTS_MAX_BRANCH_LENGTH_CM:-Inf}"
export VTS_MAX_ROUTE_TORTUOSITY="${VTS_MAX_ROUTE_TORTUOSITY:-4.0}"
export VTS_HYDRAULIC_COST_WEIGHT="${VTS_HYDRAULIC_COST_WEIGHT:-1.0}"
export VTS_HYDRAULIC_RANK_CANDIDATE_FACTOR="${VTS_HYDRAULIC_RANK_CANDIDATE_FACTOR:-4}"
export VTS_HYDRAULIC_REFERENCE_LENGTH_CM="${VTS_HYDRAULIC_REFERENCE_LENGTH_CM:-1.0}"
export VTS_HYDRAULIC_EXISTING_PATH_WEIGHT="${VTS_HYDRAULIC_EXISTING_PATH_WEIGHT:-1.0}"
export VTS_PATH_LENGTH_COST_WEIGHT="${VTS_PATH_LENGTH_COST_WEIGHT:-0.5}"
export VTS_BRANCHPOINT_DEPTH_COST_WEIGHT="${VTS_BRANCHPOINT_DEPTH_COST_WEIGHT:-0.02}"
export VTS_MIN_HYDRAULIC_SCORE_CM="${VTS_MIN_HYDRAULIC_SCORE_CM:-0.0}"
export VTS_MAX_NEW_BRANCH_RESISTANCE_REL="${VTS_MAX_NEW_BRANCH_RESISTANCE_REL:-Inf}"
export VTS_MAX_TERMINAL_PATH_RESISTANCE_REL="${VTS_MAX_TERMINAL_PATH_RESISTANCE_REL:-Inf}"
export VTS_MAX_TERMINAL_PATH_LENGTH_CM="${VTS_MAX_TERMINAL_PATH_LENGTH_CM:-Inf}"
export VTS_MAX_BRANCHPOINT_GENERATION="${VTS_MAX_BRANCHPOINT_GENERATION:-80}"
export VTS_BLOOD_VISCOSITY_POISE="${VTS_BLOOD_VISCOSITY_POISE:-0.035}"
export VTS_MIN_INITIAL_TERRITORY_FRACTION="${VTS_MIN_INITIAL_TERRITORY_FRACTION:-0.10}"
export VTS_MAX_INITIAL_TERRITORY_POINTS="${VTS_MAX_INITIAL_TERRITORY_POINTS:-8192}"

export VTS_EXPORT_FULL_GEOMETRY_CSV="${VTS_EXPORT_FULL_GEOMETRY_CSV:-false}"
export VTS_EXPORT_FULL_ARTERIAL_CSV="${VTS_EXPORT_FULL_ARTERIAL_CSV:-false}"
export VTS_TERMINAL_PATH_AUDIT_MAX_ROWS="${VTS_TERMINAL_PATH_AUDIT_MAX_ROWS:-500000}"
export VTS_TERMINAL_PATH_AUDIT_INCLUDE_SEGMENTS="${VTS_TERMINAL_PATH_AUDIT_INCLUDE_SEGMENTS:-false}"

{
    echo "run=right_leg_biology_first_explicit"
    echo "started=$(date --iso-8601=seconds)"
    echo "repo=${REPO}"
    echo "input=${INPUT}"
    echo "xcat_nrb_path=${VTS_XCAT_NRB_PATH}"
    echo "output=${OUT}"
    echo "log=${LOG}"
    echo "cuda_visible_devices=${CUDA_VISIBLE_DEVICES}"
    echo "terminal_um=${TERMINAL_UM}"
    echo "min_explicit_routed_terminal_um=${VTS_MIN_EXPLICIT_ROUTED_TERMINAL_UM}"
    echo "explicit_terminal_um=${VTS_EXPLICIT_TERMINAL_UM:-auto}"
    echo "terminal_bed_mode=${VTS_TERMINAL_BED_MODE:-auto}"
    echo "terminal_bed_diameter_um=${VTS_TERMINAL_BED_DIAMETER_UM}"
    echo "terminal_bed_length_cm=${VTS_TERMINAL_BED_LENGTH_CM}"
    echo "target=${TARGET}"
    echo "target_branch_count_mode=${VTS_TARGET_BRANCH_COUNT_MODE}"
    echo "adaptive_branch_caps=${VTS_ADAPTIVE_BRANCH_CAPS}"
    echo "allow_post_growth_subdivision=${VTS_ALLOW_POST_GROWTH_SUBDIVISION}"
    echo "graph_block_size=${GRAPH_BLOCK_SIZE}"
    echo "graph_neighbors=${GRAPH_NEIGHBORS}"
    echo "frontier_batch=${FRONTIER_BATCH}"
    echo "min_frontier_separation_cm=${MIN_FRONTIER_SEPARATION_CM}"
    echo "max_segment_length_cm=${MAX_SEGMENT_LENGTH_CM}"
    echo "max_path_nodes=${MAX_PATH_NODES}"
    echo "graph_jitter_cm=${GRAPH_JITTER_CM}"
    echo "snap_terminal_to_target=${SNAP_TERMINAL_TO_TARGET}"
    echo "max_terminal_snap_cm=${MAX_TERMINAL_SNAP_CM}"
    echo "coverage_multiplier=${COVERAGE_MULTIPLIER}"
    echo "use_indexed_anchor=${USE_INDEXED_ANCHOR}"
    echo "use_astar_routing=${USE_ASTAR_ROUTING}"
    echo "frontier_candidate_factor=${FRONTIER_CANDIDATE_FACTOR}"
    echo "fixed_vein_exports=${FIXED_VEIN_EXPORTS}"
    echo "max_anchor_gap_cm=${MAX_ANCHOR_GAP_CM}"
    echo "growth_artery_seeds=${GROWTH_ARTERY_SEEDS}"
    echo "growth_artery_min_length_cm=${GROWTH_ARTERY_MIN_LENGTH_CM}"
    echo "fixed_artery_min_length_cm=${FIXED_ARTERY_MIN_LENGTH_CM}"
    echo "fixed_vein_min_length_cm=${FIXED_VEIN_MIN_LENGTH_CM}"
    echo "path_length_cost_weight=${VTS_PATH_LENGTH_COST_WEIGHT}"
    echo "branchpoint_depth_cost_weight=${VTS_BRANCHPOINT_DEPTH_COST_WEIGHT}"
    echo "max_terminal_path_length_cm=${VTS_MAX_TERMINAL_PATH_LENGTH_CM}"
    echo "max_branchpoint_generation=${VTS_MAX_BRANCHPOINT_GENERATION}"
} > "${OUT}/run_metadata.txt"

exec /home/molloi-lab/.juliaup/bin/julia --project=. \
    examples/right_leg_xcat_50um_gpu.jl \
    "${TERMINAL_UM}" \
    "${OUT}" \
    "${VTS_XCAT_NRB_PATH}" \
    "${TARGET}" \
    "${FRONTIER_BATCH}" \
    "${GRAPH_BLOCK_SIZE}" \
    "${MIN_FRONTIER_SEPARATION_CM}" \
    "${MAX_SEGMENT_LENGTH_CM}" \
    "${GRAPH_NEIGHBORS}" \
    "${MAX_PATH_NODES}" \
    "${GRAPH_JITTER_CM}" \
    "${SNAP_TERMINAL_TO_TARGET}" \
    "${MAX_TERMINAL_SNAP_CM}" \
    "${COVERAGE_MULTIPLIER}" \
    "${USE_INDEXED_ANCHOR}" \
    "${USE_ASTAR_ROUTING}" \
    "${FRONTIER_CANDIDATE_FACTOR}" \
    "${FIXED_VEIN_EXPORTS}" \
    "${MAX_ANCHOR_GAP_CM}" \
    "${GROWTH_ARTERY_SEEDS}" \
    "${GROWTH_ARTERY_MIN_LENGTH_CM}" \
    "${FIXED_ARTERY_MIN_LENGTH_CM}" \
    "${FIXED_VEIN_MIN_LENGTH_CM}" \
    > "${LOG}" 2>&1
