#!/usr/bin/env bash
set -euo pipefail

WORK_ROOT="/media/molloi-lab/2TB4/Artin/right_leg_corrected_50um_full_20260615_1453"
REPO="${WORK_ROOT}/repo/VascularTreeSim.jl"
INPUT="${WORK_ROOT}/input/both_legs_xcat_input"
STAMP="$(date +%Y%m%d_%H%M%S)"

TERMINAL_UM="${VTS_TERMINAL_UM:-8.0}"
EXPLICIT_TERMINAL_UM="${VTS_EXPLICIT_TERMINAL_UM:-200.0}"
TARGET_200UM_BRANCHES="${VTS_TARGET_BRANCHES:-20000}"
OUT="${WORK_ROOT}/output/right_leg_original_style_${EXPLICIT_TERMINAL_UM/./p}um_to_${TERMINAL_UM/./p}um_${TARGET_200UM_BRANCHES}cco_${STAMP}"
LOG_DIR="${WORK_ROOT}/logs"
LOG="${LOG_DIR}/right_leg_original_style_${EXPLICIT_TERMINAL_UM/./p}um_to_${TERMINAL_UM/./p}um_${TARGET_200UM_BRANCHES}cco_${STAMP}.log"

mkdir -p "${OUT}" "${LOG_DIR}"
cd "${REPO}"

export JULIA_DEPOT_PATH="/media/molloi-lab/2TB4/Artin/julia_depot"
export JULIA_NUM_THREADS="${JULIA_NUM_THREADS:-16}"
export CUDA_DEVICE_ORDER="PCI_BUS_ID"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export VTS_CHECKPOINT_DIR="${OUT}/checkpoints"
export VTS_CHECKPOINT_INTERVAL_SECONDS="${VTS_CHECKPOINT_INTERVAL_SECONDS:-1800}"
export VTS_CHECKPOINT_KEEP="${VTS_CHECKPOINT_KEEP:-3}"

# Original coronary-style geometry: grow explicit CCO terminals at 200um, then
# recursively subdivide to the requested capillary/terminal scale.
export VTS_BIOLOGY_FIRST="${VTS_BIOLOGY_FIRST:-false}"
export VTS_TARGET_BRANCH_COUNT_MODE="${VTS_TARGET_BRANCH_COUNT_MODE:-explicit}"
export VTS_ALLOW_POST_GROWTH_SUBDIVISION="${VTS_ALLOW_POST_GROWTH_SUBDIVISION:-true}"
export VTS_TERMINAL_BED_MODE="${VTS_TERMINAL_BED_MODE:-false}"
export VTS_EXPLICIT_TERMINAL_UM="${EXPLICIT_TERMINAL_UM}"
export VTS_TERMINAL_BED_DIAMETER_UM="${VTS_TERMINAL_BED_DIAMETER_UM:-${TERMINAL_UM}}"

export VTS_XCAT_NRB_PATH="${VTS_XCAT_NRB_PATH:-${INPUT}/both_legs_1.nrb}"
export VTS_XCAT_VESSEL_SOURCE="${VTS_XCAT_VESSEL_SOURCE:-nrb}"
export VTS_NRB_DOMAIN_VOXEL_SPACING_CM="${VTS_NRB_DOMAIN_VOXEL_SPACING_CM:-0.1}"
export VTS_NRB_DOMAIN_SAMPLES="${VTS_NRB_DOMAIN_SAMPLES:-48,48}"
export VTS_ROUTE_DILATION_VOXELS="${VTS_ROUTE_DILATION_VOXELS:-0}"
export VTS_MAX_GRAPH_BLOCK_SIZE="${VTS_MAX_GRAPH_BLOCK_SIZE:-1}"
export VTS_MIN_GRAPH_LARGEST_COMPONENT_FRACTION="${VTS_MIN_GRAPH_LARGEST_COMPONENT_FRACTION:-0.95}"
export VTS_MAX_UNCLAIMED_TARGET_FRACTION="${VTS_MAX_UNCLAIMED_TARGET_FRACTION:-0.02}"

export VTS_TARGET_TISSUE_MODE="${VTS_TARGET_TISSUE_MODE:-soft}"
export VTS_TARGET_DEMAND_MODE="${VTS_TARGET_DEMAND_MODE:-weighted}"
export VTS_TARGET_DEMAND_WEIGHTS="${VTS_TARGET_DEMAND_WEIGHTS:-muscle=1.0,skin=0.2,fat=0.05,envelope=0.1,other_soft=0.1}"
export VTS_MAX_COVERAGE_POINTS="${VTS_MAX_COVERAGE_POINTS:-5000000}"

export VTS_DISTAL_MURRAY_GAMMA="${VTS_DISTAL_MURRAY_GAMMA:-3.0}"
export VTS_PROXIMAL_MURRAY_GAMMA="${VTS_PROXIMAL_MURRAY_GAMMA:-2.0}"
export VTS_MURRAY_TRANSITION_UM="${VTS_MURRAY_TRANSITION_UM:-200.0}"
export VTS_SUBDIVISION_MAX_LD_RATIO="${VTS_SUBDIVISION_MAX_LD_RATIO:-25.0}"
export VTS_SUBDIVISION_CLIP_BELOW_UM="${VTS_SUBDIVISION_CLIP_BELOW_UM:-50.0}"
export VTS_SUBDIVIDE_XCAT_TERMINALS="${VTS_SUBDIVIDE_XCAT_TERMINALS:-false}"

# FlowSim should use this full arterial CSV for the explicit 8um tree. The
# combined CSV with veins remains off by default to avoid feeding veins into an
# arterial flow solve.
export VTS_EXPORT_FULL_GEOMETRY_CSV="${VTS_EXPORT_FULL_GEOMETRY_CSV:-false}"
export VTS_EXPORT_FULL_ARTERIAL_CSV="${VTS_EXPORT_FULL_ARTERIAL_CSV:-true}"
export VTS_FLOW_EXPLICIT_MIN_DIAMETER_UM="${VTS_FLOW_EXPLICIT_MIN_DIAMETER_UM:-8.0}"
export VTS_TOPOLOGY_AUDIT_MIN_DIAMETER_UM="${VTS_TOPOLOGY_AUDIT_MIN_DIAMETER_UM:-0.0}"
export VTS_TERMINAL_PATH_AUDIT_MAX_ROWS="${VTS_TERMINAL_PATH_AUDIT_MAX_ROWS:-500000}"
export VTS_TERMINAL_PATH_AUDIT_INCLUDE_SEGMENTS="${VTS_TERMINAL_PATH_AUDIT_INCLUDE_SEGMENTS:-false}"

# Keep this reference run close to the original predictor. Extra flow-aware
# ranking can be enabled later after the baseline audits are understood.
export VTS_HYDRAULIC_COST_WEIGHT="${VTS_HYDRAULIC_COST_WEIGHT:-0.0}"
export VTS_HYDRAULIC_RANK_CANDIDATE_FACTOR="${VTS_HYDRAULIC_RANK_CANDIDATE_FACTOR:-0}"
export VTS_HYDRAULIC_EXISTING_PATH_WEIGHT="${VTS_HYDRAULIC_EXISTING_PATH_WEIGHT:-0.0}"
export VTS_PATH_LENGTH_COST_WEIGHT="${VTS_PATH_LENGTH_COST_WEIGHT:-0.0}"
export VTS_BRANCHPOINT_DEPTH_COST_WEIGHT="${VTS_BRANCHPOINT_DEPTH_COST_WEIGHT:-0.0}"
export VTS_MIN_HYDRAULIC_SCORE_CM="${VTS_MIN_HYDRAULIC_SCORE_CM:-0.0}"
export VTS_MAX_NEW_BRANCH_RESISTANCE_REL="${VTS_MAX_NEW_BRANCH_RESISTANCE_REL:-Inf}"
export VTS_MAX_TERMINAL_PATH_RESISTANCE_REL="${VTS_MAX_TERMINAL_PATH_RESISTANCE_REL:-Inf}"
export VTS_MAX_TERMINAL_PATH_LENGTH_CM="${VTS_MAX_TERMINAL_PATH_LENGTH_CM:-Inf}"
export VTS_MAX_BRANCHPOINT_GENERATION="${VTS_MAX_BRANCHPOINT_GENERATION:-9223372036854775807}"
export VTS_BLOOD_VISCOSITY_POISE="${VTS_BLOOD_VISCOSITY_POISE:-0.035}"
export VTS_ADAPTIVE_BRANCH_CAPS="${VTS_ADAPTIVE_BRANCH_CAPS:-false}"
export VTS_MIN_INITIAL_TERRITORY_FRACTION="${VTS_MIN_INITIAL_TERRITORY_FRACTION:-0.05}"
export VTS_MAX_INITIAL_TERRITORY_POINTS="${VTS_MAX_INITIAL_TERRITORY_POINTS:-4096}"

FRONTIER_BATCH="${VTS_FRONTIER_BATCH:-4096}"
GRAPH_BLOCK_SIZE="${VTS_GRAPH_BLOCK_SIZE:-1}"
MIN_FRONTIER_SEPARATION_CM="${VTS_MIN_FRONTIER_SEPARATION_CM:-0.01}"
MAX_SEGMENT_LENGTH_CM="${VTS_MAX_SEGMENT_LENGTH_CM:-0.05}"
GRAPH_NEIGHBORS="${VTS_GRAPH_NEIGHBORS:-24}"
MAX_PATH_NODES="${VTS_MAX_PATH_NODES:-48}"
GRAPH_JITTER_CM="${VTS_GRAPH_JITTER_CM:-0.005}"
SNAP_TERMINAL_TO_TARGET="${VTS_SNAP_TERMINAL_TO_TARGET:-true}"
MAX_TERMINAL_SNAP_CM="${VTS_MAX_TERMINAL_SNAP_CM:-0.15}"
COVERAGE_MULTIPLIER="${VTS_COVERAGE_MULTIPLIER:-1.25}"
USE_INDEXED_ANCHOR="${VTS_USE_INDEXED_ANCHOR:-true}"
USE_ASTAR_ROUTING="${VTS_USE_ASTAR_ROUTING:-true}"
FRONTIER_CANDIDATE_FACTOR="${VTS_FRONTIER_CANDIDATE_FACTOR:-32}"
FIXED_VEIN_EXPORTS="${VTS_FIXED_VEIN_EXPORTS:-6}"
MAX_ANCHOR_GAP_CM="${VTS_MAX_ANCHOR_GAP_CM:-1.25}"
GROWTH_ARTERY_SEEDS="${VTS_GROWTH_ARTERY_SEEDS:-0}"
GROWTH_ARTERY_MIN_LENGTH_CM="${VTS_GROWTH_ARTERY_MIN_LENGTH_CM:-3.0}"
FIXED_ARTERY_MIN_LENGTH_CM="${VTS_FIXED_ARTERY_MIN_LENGTH_CM:-3.0}"
FIXED_VEIN_MIN_LENGTH_CM="${VTS_FIXED_VEIN_MIN_LENGTH_CM:-8.0}"

{
    echo "run=right_leg_original_style_8um_full"
    echo "started=$(date --iso-8601=seconds)"
    echo "repo=${REPO}"
    echo "input=${INPUT}"
    echo "xcat_nrb_path=${VTS_XCAT_NRB_PATH}"
    echo "output=${OUT}"
    echo "log=${LOG}"
    echo "cuda_visible_devices=${CUDA_VISIBLE_DEVICES}"
    echo "terminal_um=${TERMINAL_UM}"
    echo "explicit_terminal_um=${VTS_EXPLICIT_TERMINAL_UM}"
    echo "target_200um_cco_branches=${TARGET_200UM_BRANCHES}"
    echo "target_branch_count_mode=${VTS_TARGET_BRANCH_COUNT_MODE}"
    echo "allow_post_growth_subdivision=${VTS_ALLOW_POST_GROWTH_SUBDIVISION}"
    echo "terminal_bed_mode=${VTS_TERMINAL_BED_MODE}"
    echo "subdivision_max_ld_ratio=${VTS_SUBDIVISION_MAX_LD_RATIO}"
    echo "subdivision_clip_below_um=${VTS_SUBDIVISION_CLIP_BELOW_UM}"
    echo "export_full_arterial_csv=${VTS_EXPORT_FULL_ARTERIAL_CSV}"
    echo "flow_explicit_min_diameter_um=${VTS_FLOW_EXPLICIT_MIN_DIAMETER_UM}"
    echo "graph_block_size=${GRAPH_BLOCK_SIZE}"
    echo "frontier_batch=${FRONTIER_BATCH}"
    echo "coverage_multiplier=${COVERAGE_MULTIPLIER}"
    echo "target_tissue_mode=${VTS_TARGET_TISSUE_MODE}"
    echo "target_demand_mode=${VTS_TARGET_DEMAND_MODE}"
    echo "target_demand_weights=${VTS_TARGET_DEMAND_WEIGHTS}"
    echo "distal_murray_gamma=${VTS_DISTAL_MURRAY_GAMMA}"
    echo "proximal_murray_gamma=${VTS_PROXIMAL_MURRAY_GAMMA}"
    echo "murray_transition_um=${VTS_MURRAY_TRANSITION_UM}"
    echo "hydraulic_cost_weight=${VTS_HYDRAULIC_COST_WEIGHT}"
    echo "hydraulic_rank_candidate_factor=${VTS_HYDRAULIC_RANK_CANDIDATE_FACTOR}"
    echo "checkpoint_dir=${VTS_CHECKPOINT_DIR}"
    echo "checkpoint_interval_seconds=${VTS_CHECKPOINT_INTERVAL_SECONDS}"
    echo "checkpoint_keep=${VTS_CHECKPOINT_KEEP}"
} > "${OUT}/run_metadata.txt"

exec /home/molloi-lab/.juliaup/bin/julia --project=. \
    examples/right_leg_xcat_50um_gpu.jl \
    "${TERMINAL_UM}" \
    "${OUT}" \
    "${VTS_XCAT_NRB_PATH}" \
    "${TARGET_200UM_BRANCHES}" \
    "${FRONTIER_BATCH}" \
    "${GRAPH_BLOCK_SIZE}" \
    "${MIN_FRONTIER_SEPARATION_CM}" \
    "${MAX_SEGMENT_LENGTH_CM}" \
    "${GRAPH_NEIGHBORS}" \
    "${MAX_PATH_NODES}" \
    "${GRAPH_JITTER_CM}" \
    "${SNAP_TERMINAL_TO_TARGET}" \
    "${MAX_TERMINAL_SNAP_CM}" \
    "${COVERAGE_MULTIPLIER}" \
    "${USE_INDEXED_ANCHOR}" \
    "${USE_ASTAR_ROUTING}" \
    "${FRONTIER_CANDIDATE_FACTOR}" \
    "${FIXED_VEIN_EXPORTS}" \
    "${MAX_ANCHOR_GAP_CM}" \
    "${GROWTH_ARTERY_SEEDS}" \
    "${GROWTH_ARTERY_MIN_LENGTH_CM}" \
    "${FIXED_ARTERY_MIN_LENGTH_CM}" \
    "${FIXED_VEIN_MIN_LENGTH_CM}" \
    > "${LOG}" 2>&1
